"""Eden OE — Text-to-Speech wrapper (Kokoro).

Provides a simple ``speak(text)`` API for TTS and an ``available()``
check.  Uses the Kokoro-82M model directly for generation and PulseAudio
(paplay) for playback.  Graceful fallback if Kokoro is not installed.

Usage:
    from eden.tts import speak, available

    if available():
        speak("Hello, welcome to Eden OE.")
    else:
        print("TTS not available — install kokoro>=0.9.4")
"""

from __future__ import annotations

import logging
import os
import subprocess
import tempfile
from pathlib import Path

logger = logging.getLogger(__name__)

# ── Defaults ──────────────────────────────────────────────────────────────
_DEFAULT_VOICE = "af_bella"  # Warm female voice — Haven's voice
_SAMPLE_RATE = 24000

# PulseAudio sink — tries wireless headset first, falls back to default
_PA_SINKS = [
    "alsa_output.usb-Logitech_PRO_X_Wireless_Gaming_Headset-00.analog-stereo",
    "@DEFAULT_SINK@",
]


# ── Public API ────────────────────────────────────────────────────────────


def available() -> bool:
    """Return True if Kokoro is installed and importable."""
    try:
        from kokoro import KPipeline  # noqa: F401

        return True
    except ImportError:
        return False


def speak(
    text: str,
    voice: str = _DEFAULT_VOICE,
    speed: float = 0.85,
    block: bool = True,
) -> bool:
    """Generate speech from *text* and play it through the system audio.

    Args:
        text:   The text to speak.
        voice:  Kokoro voice name (default: af_bella).
        speed:  Speaking speed (default: 0.85).
        block:  If True, block until playback finishes (default: True).

    Returns:
        True if speech was generated and playback started, False otherwise.

    Graceful degradation:
        - Returns False if Kokoro is not installed.
        - Returns False if audio playback fails.
        - Logs warnings on failure but never raises.
    """
    if not text:
        logger.warning("TTS: empty text, nothing to speak")
        return False

    if not available():
        logger.warning("TTS: Kokoro not installed — can't speak")
        return False

    try:
        _generate_and_play(text, voice, speed, block)
        return True
    except Exception:
        logger.exception("TTS: speak() failed")
        return False


# ── Internal ──────────────────────────────────────────────────────────────


def _generate_and_play(text: str, voice: str, speed: float, block: bool) -> None:
    """Generate audio and play it.

    Writes to a temporary WAV file, then plays with paplay.  This keeps
    the API simple — no streaming state to manage.
    """
    # Suppress torch warnings inside kokoro
    os.environ.setdefault("PIP_REQUIRE_VIRTUALENV", "0")

    from kokoro import KPipeline
    import soundfile as sf  # noqa: F811

    pipeline = KPipeline(lang_code="a", repo_id="hexgrad/Kokoro-82M")
    generator = pipeline(text, voice=voice, speed=speed)

    # Collect first audio chunk (sufficient for short messages)
    chunks: list = []
    for _, _, audio in generator:
        chunks.append(audio)
        break

    if not chunks:
        logger.warning("TTS: no audio generated by Kokoro")
        return

    audio_array = chunks[0]

    # Write to temp WAV
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        tmp_path = tmp.name
    try:
        sf.write(tmp_path, audio_array, _SAMPLE_RATE)
        _play_wav(tmp_path, block)
    finally:
        # Clean up temp file
        try:
            Path(tmp_path).unlink(missing_ok=True)
        except OSError:
            pass


def _play_wav(wav_path: str, block: bool) -> None:
    """Play a WAV file via PulseAudio (paplay).

    Tries the Logitech headset sink first, falls back to default sink.
    """
    for sink in _PA_SINKS:
        try:
            proc = subprocess.Popen(
                ["paplay", "--device=" + sink, wav_path],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            if block:
                proc.wait(timeout=60)
            return
        except FileNotFoundError:
            logger.warning("TTS: paplay not found — install pulseaudio-utils")
            return
        except Exception:
            continue

    logger.warning("TTS: no working PulseAudio sink found")


__all__ = [
    "available",
    "speak",
]
